### ISSUE TITLE
Building the app is not working

### ISSUE THREAD

**Issue by laestis** [JChemPaint/jchempaint#180]
Hi,

I strictly followed the application found here https://github.com/JChemPaint/jchempaint/wiki/Development-jcp. When I want to build the application and type "ant" to do so I ended with the following error: 

"laetitia@pivoine:~/Project/JavaApplet/jchempaint$ ant
Buildfile: /home/laetitia/Project/JavaApplet/jchempaint/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antcontrib.properties. It could not be found.
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antcontrib.properties. It could not be found.

check-languageclasses:

BUILD FAILED
/home/laetitia/Project/JavaApplet/jchempaint/build.xml:196: /home/laetitia/Project/JavaApplet/jchempaint/po does not exist."

Indeed the po directory does not exist. It was not in the git repository. What should I do?

Thanks

**Comment by johnmay** [comment]
The PO files need to be built with a GNU gettext. JChemPaint is now build using Maven which makes this more explicit.
