### ISSUE TITLE
Relayout button doesn't preserve cis-/trans- double bonds

### ISSUE THREAD

**Issue by neonfuzz** [JChemPaint/jchempaint#181]
Clicking the "relayout" button always converts cis- double bonds into trans- bonds, which can drastically change the chemistry of the drawn compound.  "Relayout" should instead preserve cis- bonds.

**Comment by johnmay** [comment]
Resolved - https://github.com/JChemPaint/jchempaint/commit/e64d095961dc259e3e483d0ff5c05414d35a00f5
