### ISSUE TITLE
Smile generated (by copy as smile) doesn't contain stereochemical information

### ISSUE THREAD

**Issue by Ichirou-Tomoe** [JChemPaint/jchempaint#186]
when copying a structure as smile, all the stereochemical information is lost: Pasting it anywhere will give a flat structure with only normal bonds. 
since the SmilesGenerator.absolute(); from CDK 1.5 does store stereochemistry, it shoul work. But the CDK  API info say it use InChI for smile generation so maybe that's the catch since your project seems to have it's own version of it?

**Comment by johnmay** [comment]
JChemPaint is no longer maintained and the CDK was only updated relatively recently to get stereochemistry working correctly. It's likely JChemPaint implemented it's own copy function, if you find where the copy happens in JChemPaint it should be easy to patch/pull requests.

**Comment by johnmay** [comment]
Resolved - https://github.com/JChemPaint/jchempaint/commit/4df606e5faf05652a5931dbc777ee237510210fc
