### ISSUE TITLE
Hydrogens on terminal hydroxyl groups are missing

### ISSUE THREAD

**Issue by tmarti02** [JChemPaint/jchempaint#188]
If I draw ethanol this is what I get:
![pic1](https://cloud.githubusercontent.com/assets/5942338/26589352/d61fe90e-4525-11e7-9bfc-79d710e75bbc.jpg)

It didn't matter that implicit hydrogens were turned on in preferences.

If I select “View…Implicit Hydrogens…On All” it just makes all the “C” atoms visible and not the H on the oxygen:

![pic2](https://cloud.githubusercontent.com/assets/5942338/26589353/d62058da-4525-11e7-99e8-d9f9bfecf47b.jpg)

**Comment by johnmay** [comment]
Dev note -> Fix with StandardGenerator

**Comment by tmarti02** [comment]
A lot of the other preferences aren't working either- such as "show aromatic ring circles" and "draw atom numbers"

**Comment by johnmay** [comment]
Resolved primary problem -
 https://github.com/JChemPaint/jchempaint/commit/098615a6c7b50a65722900b67bbd22f1fc8b0e4c

![image](https://user-images.githubusercontent.com/983232/30113786-c3164476-930d-11e7-8619-6aee17bbc2b9.png)

StandardGenerator works but needs more testing

![image](https://user-images.githubusercontent.com/983232/30113791-c8a9d1d2-930d-11e7-92ca-9f1cd44fc477.png)

**Comment by tmarti02** [comment]
Awesome thank you!!!

**Comment by tmarti02** [comment]
Oddly now when chemicals are loaded from mol files, the valency is shown for each atom 

![image](https://user-images.githubusercontent.com/5942338/30129139-f713b254-9312-11e7-9848-11b3b657c561.png)

**Comment by johnmay** [comment]
Can you open a separate issue, this is easy to fix just a conflict in how things used to be done vs are done now (mdl valence models etc).

**Comment by johnmay** [comment]
Fixed now https://github.com/JChemPaint/jchempaint/commit/46e05390c36748a84580e50539797d94611a6e51

**Comment by tmarti02** [comment]
OK then you can close the issue I just created :).
