### ISSUE TITLE
copy/paste not working on MacOS

### ISSUE THREAD

**Issue by mkrompiec** [JChemPaint/jchempaint#194]
Copy/paste isn't working for me, even within the same JChemPaint window. I get an InvalidSmilesException, regardless of what I'm trying to copy/paste. I'm using openjdk 17 2021-09-14 on MacOS 11.6.
![jchempaint_error](https://user-images.githubusercontent.com/16683215/136600187-37106798-8ce2-466e-9f71-7e698a8955a7.png)
.

**Comment by johnmay** [comment]
Where you using JDK 15? JDK 8, 11, and now 17 are the stable. More recent java versions are removing older APIs and restrict reflective access. Rebuilding with the target JVM would work but using JDK 8 it should function fine.

**Comment by johnmay** [comment]
OK. We warned other bits might randomly not work
